on:
  push:
    branches:
      - main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDFs 
          tinytex: true 
          # uncomment below and fill to pin a version
          # version: 0.9.600
      
      - name: Render
        run: |
          quarto render GitHub-SOP.qmd --to html
          quarto render GitHub-SOP.qmd --to pdf
        shell: bash

     - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
